# permissions for end users to view cointracpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cointrac-operator
    app.kubernetes.io/managed-by: kustomize
  name: cointracpipeline-viewer-role
rules:
- apiGroups:
  - cointrac.cointrac.operator
  resources:
  - cointracpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cointrac.cointrac.operator
  resources:
  - cointracpipelines/status
  verbs:
  - get
